export { default as Hero } from './Hero';
export { default as Nav } from './Nav';
export { default as Burger } from './Burger';
export { default as Menu } from './Menu';
export { default as Projects } from './Projects';
export { default as Introduction } from './Introduction';
export { default as Footer } from './Footer';
export { default as Skills } from './Skills';
export { default as ContactForm } from './ContactForm';
